### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by fahadfaisal4** [w9w/JSA#12]
Hi there,

Thanks for creating a wonderful tool for automating this tasks.

While I run jsa.py, I am getting this error :

```
Traceback (most recent call last):
  File "/usr/sbin/jsa.py", line 11, in <module>
    from tld_detection import tld_detection
ModuleNotFoundError: No module named 'tld_detection'
```

So I tried to I install the 'tld_detection' module, but that was also failed:
```
pip3 install tld_detection -v
Created temporary directory: /tmp/pip-ephem-wheel-cache-86glbg7_
Created temporary directory: /tmp/pip-req-tracker-oucuturg
Created requirements tracker '/tmp/pip-req-tracker-oucuturg'
Created temporary directory: /tmp/pip-install-o9bb2xnc
Collecting tld_detection
  1 location(s) to search for versions of tld-detection:
  * https://pypi.org/simple/tld-detection/
  Getting page https://pypi.org/simple/tld-detection/
  Looking up "https://pypi.org/simple/tld-detection/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/tld-detection/ HTTP/1.1" 404 13
  Status code 404 not in [200, 203, 300, 301]
Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 572, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 530, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 675, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 793, in _get_page
    return _get_html_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 147, in _get_html_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/tld-detection/

```

Looks like the module is not available now!

Thanks for your time ;)

**Comment by fahadfaisal4** [comment]
Sorry, It was fixed after I executed the installations.sh
